### PR TITLE
Fix compilation issues

### PR DESCRIPTION
**Pull request by benfgit**
Fixed compilation issues and created Github Actions CI pipeline for this repo.

### CODE REVIEW

**Comment by benfgit** [comment]
Compilation fails, [here is the CI output](https://github.com/falcon-eyrie/falcon-fklab-extensions/actions/runs/19469054396/job/55711116685?pr=84).

```
/home/runner/work/falcon-fklab-extensions/falcon-core/extensions/falcon-fklab-extensions/processors/distributor/distributor.cpp:155:27: error: ‘class nsTimeSeries::Data<double>’ has no member named ‘clone_column’; did you mean ‘end_column’?
  155 |                 data_out->clone_column(ch, *data_in);
      |                           ^~~~~~~~~~~~
      |                           end_column
```

@MarineChap do you have an idea?

Also I'm confused about which branch I'm supposed to use for `falcon-fklab-extensions` repo. What is the most updated one? `master`, `develop`, `1.3.1`?

**Comment by MarineChap** [comment]
Did you mix falcon-core/master and extension/develop? 

Official releases goes with the master branch 
Master / 1.3.1
And develop branches goes together 
Develop/develop 

That should fix your problem hopefully

**Comment by benfgit** [comment]
In this PR, I created a separate CI pipeline for this repo (fklab).

I've branched from `fklab/develop` and trying to merge back to it. [The new pipeline for fklab](https://github.com/falcon-eyrie/falcon-fklab-extensions/blob/3e1247db0363d0bccc65744b9681410639da7c7d/.github/workflows/build.yml#L21) fetches the `falcon-core/develop`. Then links `fklab/develop` to `falcon-core/develop` locally. And builds the `falcon-core/develop` after.

I also get the same compilation error on my local.

**Comment by benfgit** [comment]
@MarineChap Do you have an idea? Which branch is working for you?

**Comment by MarineChap** [comment]
Good afternoon, 
I am on a big project this week, I really cannot spare time for falcon right now. 
Maybe next week I can take a look.
Have a good day

**Comment by benfgit** [comment]
Thanks for the reply. :+1:

**Comment by benfgit** [comment]
Hi,

Is it possible to look into this issue this week?

**Comment by dcili** [comment]
@MarineChap : did you have any time to look into the issue? We just need to know on which branch we should take the development.

**Comment by MarineChap** [comment]
Checkout this PR #75 - look like the clone_column function was developped here. 

And about why a PR, using a feature not merged in develop, has been merged in develop... I have no idea.

**Comment by MarineChap** [comment]
After looking at the develop branch in bitbucket (I prefer their graph commit view usually), I would advise to rebase the develop branch to the commit  e31c77d. 
It would remove the last merged PRs that are suspicious and was probably more meant to merged at the same time as all the other branches developped for the decoding application. (would be nice to reopen the PRs closed however if you do that).

**Comment by dcili** [comment]
@MarineChap : thanks a lot for your help

**Comment by benfgit** [comment]
Thanks @MarineChap.

I have backed up the previous `develop` into [develop-from-bitbucket](https://github.com/falcon-eyrie/falcon-fklab-extensions/tree/develop-from-bitbucket) and then resetted it back to [e31c77d](https://github.com/falcon-eyrie/falcon-fklab-extensions/commit/e31c77d603205973a9cf7ffa6a55d0f1294dbfda).

When we have time, we can try to look into the backup branch and see how we can restore those commits.

Can you approve this PR?

**Comment by MarineChap** [comment]
I am not sure we should restore the commits from the previous develop branch. They are part of the test_decoding branch and should stay with this branch. 
It is more once you have a stable falcon, you will have to decide if you want to integrate all the decoding related change (and it is  huge) and in the later case, just merging test_decoding branch would be enough.

File: .github/workflows/build.yml [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Clone falcon-core repository
+        run: |
+          cd ..
+          git clone --depth 1 https://github.com/falcon-eyrie/falcon-core.git
+          cd falcon-core
+          git checkout 06c07c1218a29d1420867556317b543b98d2a28b
+          cd ..
```
Comment (MarineChap) [inline .github/workflows/build.yml:22]: I have problem with the pipeline having a fix commit. 

How you will handle the master branch to run with the falcon core master branch and the develop branch to run with the falcon core develop branch ?

Comment (benfgit) [reply .github/workflows/build.yml:22]: I removed the hardcoded commit hash. `falcon-fklab-extensions/develop` points to `falcon-core/develop`

In the future, there will be another pipeline for `falcon-fklab-extensions/main` that will point to `falcon-core/main`.

Comment (MarineChap) [reply .github/workflows/build.yml:22]: Can you automatize it with the github.base_ref variable ?

Comment (benfgit) [reply .github/workflows/build.yml:22]: Yes that's possible.

However, I was planning to create a separate pipeline like `release_main.yml` for the main branch. It'll be easier to discuss once we get there.

I'd like to merge this PR as is and make the repo compile.

**Review by MarineChap — APPROVED** [review]
